---
title: "earlyamknow"
author: "George Oberle"
date: "January 16, 2015"
output: html_document
---

Using RStudio there are several packages that are useful to load.
```{r}
#Load tools
library (sp)
library (rgdal)
library (rgeos)
library (maptools)
library (ggmap)
library (ggplot2)
library (mullenMisc)
library (magrittr)
library (stringr)
library (dplyr)
library (RColorBrewer)
library (igraph)
```

```{r}
schol_soc_geocoded <- read.csv("~/societiesnetwork/data/schol-soc-geocoded.csv")
```

```{r}
#Get the Shape files read and make sure that they work using these commands.
map_sp <- readOGR("nhgis-shp/", "state_1840")
class(map_sp)
str(map_sp, max.level = 2)
map_sp@bbox
map_sp@proj4string
head(map_sp@data)
plot(map_sp)

map1840<- readOGR ("nhgis-shp" , "state_1840")
fort2<- fortify (map1840)
```


```{r}
map_sp <- readOGR("nhgis-shp/", "state_1830")
class(map_sp)
str(map_sp, max.level = 2)
map_sp@bbox
map_sp@proj4string
head(map_sp@data)
plot(map_sp)

map1830<- readOGR ("nhgis-shp" , "state_1830")
fort1<- fortify (map1830)
```

```{r}
ggplot () + geom_map(data=fort2, map=fort2, aes(x=long, y=lat, group=group, map_id=id), color="grey", fill="white") +geom_point(data=schol_soc_geocoded, size=3, aes (x=lon, y=lat, color=Society) ) + coord_map() +ggtitle('Early American Learned Societies by Type 1768-1848')
```


```{r}
map_sp2 <- readOGR("nhgis-shp/", "US_state_1790")
class(map_sp2)
str(map_sp2, max.level = 2)
map_sp2@bbox
map_sp2@proj4string
head(map_sp2@data)
plot(map_sp2)
```

1790 County Map of US from NHGIS
```{r}
map_sp3 <- readOGR("nhgis-shp/", "US_county_1790")
class(map_sp3)
str(map_sp3, max.level = 2)
map_sp3@bbox
map_sp3@proj4string
head(map_sp3@data)
plot(map_sp3)
```

```{r}
map_sp4 <- readOGR("nhgis-shp/", "US_county_1800")
class(map_sp4)
str(map_sp4, max.level = 2)
map_sp4@bbox
map_sp4@proj4string
head(map_sp4@data)
plot(map_sp4)
```

```{r}
map_sp5 <- readOGR("nhgis-shp/", "US_state_1800")
class(map_sp5)
str(map_sp5, max.level = 2)
map_sp5@bbox
map_sp5@proj4string
head(map_sp5@data)
plot(map_sp5)
```

```{r}
map_sp6 <- readOGR("nhgis-shp/", "US_state_1810")
class(map_sp6)
str(map_sp6, max.level = 2)
map_sp6@bbox
map_sp6@proj4string
head(map_sp6@data)
plot(map_sp6)
```

```{r}
map_sp7 <- readOGR("nhgis-shp/", "US_county_1810")
class(map_sp7)
str(map_sp7, max.level = 2)
map_sp7@bbox
map_sp7@proj4string
head(map_sp7@data)
plot(map_sp7)
```

```{r}
map_sp8 <- readOGR("nhgis-shp/", "US_state_1820")
class(map_sp8)
str(map_sp8, max.level = 2)
map_sp8@bbox
map_sp8@proj4string
head(map_sp8@data)
plot(map_sp8)
```

```{r}

map_sp9 <- readOGR("nhgis-shp/", "US_county_1820_conflated")
class(map_sp9)
str(map_sp9, max.level = 2)
map_sp9@bbox
map_sp9@proj4string
head(map_sp9@data)
plot(map_sp9)

```

